### ISSUE TITLE
Security issue - sensitive data in git history

### ISSUE THREAD

**Issue by tbobm** [alexiscolin/hepic-app#6]
Hi :wave:

The commits:
- 465aa8386cee0ce45444168c0014f4e466cf39ba
- 5aeb2430168d6a017c37648b2f3c163934d39a7a
- 3f0488b8494acdfed5cee51ad11e604a357d0e3a

Do not remove the file from the history. I hope this is OK considering this looks like an "old" project :)

In case you're looking for a [more efficient solution](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository)

Hope you're doing great !

cheers,
Bob

**Comment by alexiscolin** [comment]
Hi Bob 👋 
Thank you for your issue. 

You're right, I did it on purpose, even if it's not a good practice, cause this project is not online anymore and also because these keys are not valid since a long time. No security issue here, just wanted fast repository cleaning for presentation ;)

Hope to see you soon again !
Alexis
